UniversityAspMVC/Controllers/GroupController.cs
using System;
using BL;
using Microsoft.AspNetCore.Mvc;
using Repositories;

namespace WebApp.Controllers
{
    public class GroupController : Controller
    {
        IGroupRepository _repository;
        // GET
        public IActionResult Index()
        {
            return View(GroupViewModel.GetGroups(_repository));
        }
        
        public GroupController(IGroupRepository repository)
        {
            _repository = repository;
        }
        

        public IActionResult Create(GroupViewModel model)
        {
            if (model.IsEmpty())
                return View(model);

            _repository.AddItemAsync(model);
            return Redirect("Index");
        }

        public IActionResult Edit(Guid? Id)
        {
            if (Id.HasValue)
            {
                
                return View(GroupViewModel.GetGroupById(_repository, Id.Value));
            } return NotFound(); 
        }

        public IActionResult Delete(Guid? id)
        {
            if (id.HasValue)
            {
                return View(GroupViewModel.DeleteGroup(_repository, (Guid)id));
            } return NotFound(); 
        }
    }
}

UniversityAspMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Faculties()
        {
            return View();
        }
    }
}

UniversityAspMVC/Controllers/StudentController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using BL;
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Repositories;

namespace WebApp.Controllers
{
    public class StudentController : Controller
    {
        IStudentRepository _repository;
        // GET
        public IActionResult GetAll()
        {
            return View(StudentViewModel.GetStudents(_repository));
        }
        
        public IEnumerable<StudentViewModel> GetAllApi()
        {
            return (StudentViewModel.GetStudents(_repository)).ToList();
        }
        
        public StudentController(IStudentRepository repository)
        {
            _repository = repository;
        }
        

        public IActionResult Create(StudentViewModel model)
        {
            if (model.IsEmpty())
                return View(model);

            _repository.AddItemAsync(model);
            return Redirect("GetAll");
        }

        public IActionResult Edit(StudentViewModel model)
        {
            if (model!=null)
            {
                if (_repository.ChangeItemAsync(model) != null)
                {
                    return Redirect("GetAll");
                }
            } return NotFound(); 
        }

        public IActionResult Delete(Guid? id)
        {
            if (id.HasValue)
            {
                return View(StudentViewModel.DeleteStudent(_repository, (Guid)id));
            } return NotFound(); 
        }

      
    }
}

UniversityAspMVC/Views/Group/Create.cshtml
@model BL.GroupViewModel
@using Repositories
@inject IFacultyRepository _faculties;
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Create new group</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Name</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger">The Name field is required.</span>
            </div>
            <div class="form-group">
                <label asp-for="FacultyId" class="control-label">Select Faculty</label>
                <select asp-for="FacultyId" class="form-control">
                    @foreach (var faculty in _faculties.AllItems)
                    {
                        <option value="@faculty.Id">@faculty.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

UniversityAspMVC/Views/Group/Delete.cshtml
@model bool

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

UniversityAspMVC/Views/Group/Edit.cshtml
@model BL.GroupViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

UniversityAspMVC/Views/Group/Index.cshtml
@model System.Linq.IQueryable<BL.GroupViewModel>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<h2>Groups</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        @* <th> *@
        @*     @Html.DisplayNameFor(model => model.) *@
        @* </th> *@
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

UniversityAspMVC/Views/Home/Faculties.cshtml
@using Repositories
@inject IFacultyRepository _faculties;
@model Entities.Faculty
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<table class="table table-hover">
    <thead>
    <tr>
        <th>
            Name
        </th>
    </tr>
    </thead>
    @foreach (var faculty in _faculties.AllItems)
    {
        <tr>
            <td>
                @faculty.Name
            </td>
        </tr>
    }
</table>

UniversityAspMVC/Views/Home/Index.cshtml
@page
@model WebApp.Views.Home.Index

@{
    Layout = "_Layout";
}
<div class="container " style="background: #20c997; text-align: center; padding: 10px; border-radius: 7px; ">
    <div class="row">
        <div class="col-md-auto">
            <div id="logo1">
                <img src="/images/tree2.gif" id="treeGif" alt="" onmouseover="resetAnimation();">
            </div>
        </div>
        <div class="col-md-auto">
            <h2>Innovating Ecology University</h2>
        </div>
    </div>
</div>
@* <div class="container" style="justify-content: center; border-radius: 7px; "> *@
@*      *@
@* </div> *@

<script>
// hack for not caching .gifs in ff/chrome etc.
let resetAnimation = function resetAnimation() {
  let treeGif = document.getElementById("treeGif");
  treeGif.src = treeGif.src;
};
</script>

UniversityAspMVC/Views/Index.cshtml
@page
@model IndexModel
@{
    Layout = "_Layout";
    ViewData["Title"] = "Home page";
}



<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UniversityAspMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - UniversityAspMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body style="background-image: url('//images//screen2.jpg')">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-page="/Index">UniversityAspMVC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-action="GetAll" asp-controller="Student">Students</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-action="Index" asp-controller="Group">Groups</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-action="Faculties" asp-controller="Home">Faculties</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-page="/Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-page="/Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2021 - UniversityAspMVC - <a asp-area="" asp-page="/Privacy">Privacy</a>
    </div>
</footer>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>

UniversityAspMVC/Views/Student/Create.cshtml
@using Repositories
@inject IGroupRepository _groups;
@model BL.StudentViewModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Create new student</h2>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label">First Name</label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger">The First Name field is required.</span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label">Last Name</label>
                <input asp-for="LastName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label">Select Group</label>
                <select asp-for="GroupId" class="form-control">
                    @foreach (var group in _groups.AllItems)
                    {
                        <option value="@group.Id">@group.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="GetAll">Back to List</a>
</div>

UniversityAspMVC/Views/Student/Delete.cshtml
@model bool

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

UniversityAspMVC/Views/Student/Edit.cshtml
@model BL.StudentViewModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

UniversityAspMVC/Views/Student/GetAll.cshtml
@model System.Linq.IQueryable<BL.StudentViewModel>


@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<h2>Students</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        @* <th> *@
        @*     @Html.DisplayNameFor(model => model.) *@
        @* </th> *@
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |*@
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
            <td>
               <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                                   Edit
                               </button>
            </td>
        </tr>
        
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Editing student</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form asp-action="Edit" method="post" id="editStudent"
                              name="editStudent">
                            <div class="form-group">
                                <label for="firstName" class="col-form-label">First name:</label>
                                <input type="text" class="form-control" name="firstName" id="firstName"
                                       value="@item.FirstName" required>
                                <label for="firstName" class="col-form-label">Last name:</label>
                                <input type="text" class="form-control" name="lastName" id="lastName"
                                       value="@item.LastName" required>
                            </div>
                            <input type="hidden" name="Id" value="@item.Id"/>
                            <input type="hidden" name="GroupId" value="@item.GroupId"/>
                            <input type="hidden" name="GroupName" value="@item.GroupName"/>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" onclick="form_submit() " class="btn btn-primary">Save</button>
                    </div>
                </div>
            </div>
        </div>
    }
    </tbody>
</table>
<script>
    $('#exampleModal').on('show.bs.modal', function (event) {
        //let button = $(event.relatedTarget) // Button that triggered the modal
        //let recipient = button.data('whatever') // Extract info from data-* attributes
        // let modal = $(this)
    });

    function form_submit() {
        document.getElementById("editStudent").submit();
    }
</script>